name: tag push run
on:
  push:
    tags:
      - '**'
      - '!**-beta'
      - '!**-beta*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4