name: tag push run
on:
  push:
    tags:
      - '**'
    tags-ignore:
      - '**-beta'
      - '**-beta*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4