name: tag push run
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  createZipQas:
    if: contains(github.ref, 'qas')
    runs-on: ubuntu-latest
    steps:
      - name: Zip the release
        id: create_zip_qas
        run: |
          echo "create dummy zip file"
          echo "qas" > dummy.txt
          zip dummyqas.zip dummy.txt
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dummyqas.zip
          path: dummyqas.zip

  createZipStg:
    if: contains(github.ref, 'stg')
    runs-on: ubuntu-latest
    steps:
      - name: Zip the release
        id: create_zip
        run: |
          echo "create dummy zip file"
          echo "stg" > dummy.txt
          zip dummystg.zip dummy.txt

  createGitHubRelease:
    if: needs.createZipQas.result == 'success' || needs.createZipStg.result == 'success'
    needs: [ createZipQas, createZipStg ]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release page
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v6
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}

  uploadAssetsQas:
    if: ${{ contains(github.ref, 'qas') }}
    needs: [createGitHubRelease]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Download STG artifact
        uses: actions/download-artifact@v2
        with:
          name: dummyqas.zip
          path: .
      - name: Upload the release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.createGitHubRelease.outputs.upload_url }}
          asset_path: ./dummyqas.zip
          asset_name: dummyqas.zip
          asset_content_type: application/zip

  uploadAssetsStg:
    if: ${{ contains(github.ref, 'stg') }}
    needs: [createZipStg, createGitHubRelease]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Download STG artifact
        uses: actions/download-artifact@v2
        with:
          name: dummystg.zip
          path: .
      - name: Upload the release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.createGitHubRelease.outputs.upload_url }}
          asset_path: ./dummystg.zip
          asset_name: dummystg.zip
          asset_content_type: application/zip