name: tag push run
on:
  push:
    tags:
      - '**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  createGitHubRelease:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Create Release page
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v6
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}

  release:
    needs: createGitHubRelease
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Zip the release
        run: |
          echo "create dummy zip file"
          echo "dummy" > dummy.txt
          zip dummy.zip dummy.txt
      - name: Upload the release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dummy.zip
          asset_name: dummy.zip
          asset_content_type: application/zip

